CREATE TABLE MOCK_DATA_T
(
    ID          BIGINT(20)   NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(255) NOT NULL DEFAULT '',
    CREATE_TIME DATETIME     NOT NULL,
    REVISION    INT(11)      NOT NULL,
    PRIMARY KEY (ID)
)
    ENGINE = InnoDB;

